# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "d5OqM3wT0Y60atmg+bIFupSqN4FG9H21tH2NEkmh/mPdh/M1yjuXxygRNsbsQweSNVuXapliq+/rw7XQT93HmvNdh7EQ1F2qnbJ3Miw4yEYXYxj8nPKEvO6KxnTHtk/T+cD7zI26MQsFi7BanX3knXxBnvyhsUfGazFxyGAhJjxJr5Y6S6wO/1iwE1TjBCmZYeP6wQxOGlZJi332DZ4ARmrswhHrUek1bYsfcCn452x6UBiFHyYFFiApYgbaJHc4B6mgg168qfWYYQBupjHGmBndZfLbrcEhmDy3XjpxQIzlIVIuD2gSs8OtY5S51UZIcnba6BD1Q7LKgEmEBgj6KqkinDPO1/W7hdYF2lFndCKEMP/L3Dqupl3tVHZ9hkH/WsctvWo/+s1MP2hiwSnkr3slaz5kCTf9hPPlui74JUCObu942rIAVmXTP8x8atEIcvBnVd3FGAVtTkj4oDvk8BZP+0WFBLUxd0oLX6gPEnrFmdf+jkW4yqyx1Pxwt8JCIUYbMVOfgxj4ZcoustXJ0jdPSrjgfzEPan6RGkAJQidHnjvPMykS7nWaZULx7OTrBM8kfXujJ5jXGDFmGNtUgA9F8vpMhdxDn8gUiGbbil92VE2nHPegcbh7jFTfMkw/tYxhTQuJkd0Ttac0cylBqnZDK4NaY+8xNH3efhmdK0k="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
